### ISSUE TITLE
Invite by email : Trigger duplicate DM with the same user

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#79] opened 2022-06-28 14:23 UTC
At least one broken feature :
 - Create a DM with an existing user. 
 - Create another DM with the same user, by email
 - the 2nd DM is created. The user is properly displayed (the matrixID has been found). You now have two identical DMs with the same person.
 
 Why is this happening ? The Identity Server should be doing the lookup of the email, to find the corresponding matrixId. It doesn't do it because we have not configured the IS (does the client know the url of the IS server ?) and we have not trusted it (accepted the terms and conditions). This is the "discovery" feature.
 
 Find what other features using by email are broken.
 
 More information on : https://github.com/vector-im/element-web/issues/23353

**Comment by estellecomment** [comment] 2022-07-06 09:59
Do we have this in v2?

**Comment by giomfo** [comment] 2022-07-06 11:45
> Do we have this in v2?

No, because "lookup" request is supported in v2
This is related to the "Discovery" option :  we should trust by default the id serveur imposed by Tchap HS (the TAC included this id server use). We were thinking about a change in server side to trust it by default on account creation

**Comment by estellecomment** [comment] 2022-07-18 08:55
Note : if it's simpler, we could consider just disabling invitation by email in the beta...

**Comment by estellecomment** [comment] 2022-07-18 15:45
@giomfo : the user with which I have created the double DM (as described above) should already have discovery working : it's a user created in tchap v2.
So I'm not sure why tartine is doing this. 🤔

**Comment by estellecomment** [comment] 2022-07-18 15:52
- [ ] Confirm : when you start a DM by email, there is custom code in tchap v2 that looks up the matrixId, and directs the user to the pre-existing DM with this matrixID. This avoids creating two parallel DMs.
 - [ ] Should Tchap keep this custom feature ?
 - [ ] If yes, how do we reimplement it in Tartine ?

**Comment by estellecomment** [comment] 2022-07-18 15:54
Note : for beta bucheron, we only deal with users who have a previously created account. So accepting discovery is already done.
(but it doesn't solve this problem)

**Comment by estellecomment** [comment] 2022-09-22 13:16
Note : this could be present in element, or not. Investigate to clarify the issue.

**Comment by giomfo** [comment] 2022-09-26 09:01
> Note : this could be present in element, or not. Investigate to clarify the issue.

I reproduced the issue in Element-Web. No lookup is triggered on client side. I created https://github.com/vector-im/element-web/issues/23353

**Comment by giomfo** [comment] 2023-02-17 10:32
FYI https://github.com/vector-im/element-web/issues/23353 has been fixed
Those will be included in the next release 1.11.24

**Closed as completed** 2023-04-04 09:47 UTC
Labels: web, proposal to element, needs investigation
