### ISSUE TITLE
Can't load this message (m.room.message)

### ISSUE THREAD

**Issue by mcalinghee** [tchapgouv/tchap-web-v4#146] opened 2022-08-31 13:44 UTC
### Problem
On some channel, some messages cannot be displayed on tchap-web
<img width="1208" alt="Screenshot 2022-08-31 at 14 43 53" src="https://user-images.githubusercontent.com/3725676/187691640-5f70bd6e-99ef-4b9d-9e42-c29844850ea7.png">

Whereas the message that should be displayed on tchap-iOS) should be this one : 
![IMG_B7ADBA1A79C4-1](https://user-images.githubusercontent.com/3725676/187693346-b8adfc76-0e8d-48f3-a520-509733192fd1.jpeg)

Error log : 
```
rageshake.ts:73 TypeError: this.messageContent is not a function
    at f.render (MImageReplyBody.tsx:53:32)
    at Ga (react-dom.production.min.js:187:188)
    at ja (react-dom.production.min.js:186:173)
    at Gs (react-dom.production.min.js:269:427)
    at Tl (react-dom.production.min.js:250:347)
    at yl (react-dom.production.min.js:250:278)
    at El (react-dom.production.min.js:250:138)
    at hl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
```

**How to reproduce it**
1/On ios/android : reply to a an 'image' message with a text => on tchap-web-v4 , the message is not displayed and show `Can't load this message (m.room.message) Submit logs`
2/ The reply to does not work on an image

**Comment by odelcroi** [comment] 2022-10-11 07:32
Duplicate of https://github.com/tchapgouv/tchap-web-v4/issues/159

**Closed as completed by odelcroi** 2022-10-11 07:32 UTC
Labels: bug, web
